# Site settings
title: Eveline Mariz
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Eveline Mariz
user_description: Trabalho na Companha Energética de Minas Gerais (Cemig) há 13 anos, atuando nas áreas de perdas comerciais, adimplência, arrecadação e gestão contábil. O mestrado em matemática tem sido uma oportunidade de aprofundar meus conhecimentos na área e conhecer um ambiente diferente da minha atuação profissional atual>
user_title: Mestranda em Matemática
email: evejbm@gmail.com
# twitter_username: evelinemariz
# github_username:  evelinemariz
# gplus_username:  evelinemariz

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
